language: go
go:
- '1.5'
sudo: true
env:
  global:
  - CF_APP=cloudcofeedback
  - CF_API=https://api.ng.bluemix.net
  - secure: "PtgzdX/hMi6jBh+kMB1q53z0TIQW32Xj+F0nBAPWz+8txW05PYf/T0EG17fGy5nVlq31i4tUdXs3h8IZn/q3s1OZ+JLX1YbXYqnGMaqP3+BY6y05H7abxcJ/FZCb1dRPwoMRlK3yV8jlep4G+BqdgHBmYqNuV02QkxhL9OJf4oQ8bkW3guGxeXfbnH0l0qmIo9Ez13HHVui9BCjNdW9yeDTv5ZIRVcKQx7y8KVpFe/OXaa6Wd4QNesZDIaGZpyf2Jh0/8cuD8mj7MgjJMWQ9QNoi4vMSTBDBxihMTIQ0irUKXuQa811INyZhFE/yiiEso3X/irdKOgq8u1inPbhtkgDK28AbAgmhOjQWY13O86ci/R9SUR5QD5ZNLEco6TIKGaD2tGLB4X8IBYM8yhc4KyzQv97wtS9EtPTF0SG6AEHrvvGtP8ehc3JBdxZIPpAoCZelXsUgjfC4+SlHXy1lk6TjZRnP7AsqG7u49d5DRu1ohkF3yInA2R0zRczkuLFiQ3cpYTGdQOAzfN4YOur+1+jvKvmts++Ewqvwfsr0cDqBFSa4znUEd5Tuz/ylGcAEp0zmiYw788lwYuu0vjTxl/UNIDWe64dgBCAyH48/XHZzV0/VU7yXrd2Jw9jeNYTPsEksUAbfoCgtpQg595pTNaMhyLrMPVEtXqnhZG+7Poo="
  - CF_ORGANIZATION=Dev-Advocates
  - CF_SPACE=prod
  - secure: "Lf1OBhYPIcUnmA27eups+XQVt1gWbKyjcvc3jWlYlmSk1eqqZzXxc2AGatOIEY8BZKLODPvTmpIzELsL27kjDPYsMKW/qpJQFGuLsXJXjUNoTcvKjW/NHnpeVB12FrMUICzSbnFYKlzy7TT5+KKmUYDbQUk9GoSZbQ92SawfSTie0+rtyNl2SbtfLFJsJ/o2JCGEw7MjoofSHF+Rf7CIFUrQPKN2RbOL5D1nBmi1+VsfNJhNGQs4ZW8RYGRlRHU8UkxAwh0TjSy/MYsMqwqABA4R1BA+MhPzrnLAAKRcOB9fZ38IuNwFdKgxJqNc4I4NMDFVl721LrMspE8FCslTZErpSXh9NoYuHRSz7TnLd7VbMMwJ4x2AyeqLPorQcaog7hoQyrUlaCayS8k6TzrUEc7lIUbCzvE7BOT1Y7A6f2hScTXVwUbt5mxeC5S5Wl0Dyy6PGdQflyligy+eub9tgNyaex9w/Nhnt0IU5WrAABRZcDTanBtGunW9szEwPX/C0cCmYXc4mD4jb3+TkdXQNed6s2P5na0DG1k6v0K2N1vvMi9vueXlxLIEgg+gXTGLgj3DtMnDAI95tdTmHEJ6y8RqmAeBgoNiNTR1JEWsiq21+wVJZMBPz2ehVp3tOPih++UTmdEaER9hY+OPV3GGpi/029SOvo6DRg+NMjVnJNY="
before_deploy: npm install -g cf-blue-green
deploy:
  provider: script
  script: cf-blue-green-travis
  on:
    branch: master
    repo: IBM-Bluemix/cloudcofeedback
